services:
  postgres_db:
    image: postgres:16-alpine
    container_name: personal_finance_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=personal_finance
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./finance_app
    container_name: personal_finance_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/personal_finance
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres_db

volumes:
  postgres_data: