apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-api
  template:
    metadata:
      labels:
        app: finance-api
    spec:
      containers:
        - name: finance-api
          image: finance-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: finance-api-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: finance-api
spec:
  selector:
    app: finance-api
  ports:
    - port: 8080
      targetPort: 8080
