apiVersion: gateway.api-platform.wso2.com/v1alpha1
kind: RestApi
metadata:
  name: finance-api-v1.0
spec:
  displayName: Finance-API
  version: v1.0
  context: /finance/$version
  upstream:
    main:
      url: http://finance-api.default.svc.cluster.local:8080
  operations:
    - method: GET
      path: /transactions
    - method: POST
      path: /transactions
    - method: GET
      path: /summary
    - method: GET
      path: /budgets/status
